---
apiVersion: v1
kind: Pod
metadata:
  name: kiada
spec:
  containers:
     - name: kiada
       image: techwithprerit/k8s-hindi-app1:1.2-major
       imagePullPolicy: Always
       Ports:
         - containerPort:8080
