---
apiVersion: v1
kind: Pod
metadata:
  name: kiada
spec:
  containers:
    - name: kiada
      image: techwithprerit/k8s-hindi-app
      imagePullPolicy: Always
      Ports:
        - containerPort:8080
